ALTER TABLE event ADD COLUMN page_title TEXT;
ALTER TABLE event ADD COLUMN hostname TEXT;
ALTER TABLE event ADD COLUMN lcp REAL;
ALTER TABLE event ADD COLUMN inp REAL;
ALTER TABLE event ADD COLUMN cls REAL;
ALTER TABLE event ADD COLUMN ttfb REAL;
ALTER TABLE event ADD COLUMN val REAL;
